apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: openai
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: openai
spec:
  source:
    git:
      url: https://github.com/cpage-pivotal/explore-demo
      ref:
        branch: main
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
  - name: openai
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: openai-claim
